apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: tree-v2
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 8545
      - protocol: "TCP"
        targetPort: 31337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            securityContext:
              privileged: false
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: false
  allowConnectTo:
    - tree-v2
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: eu.gcr.io/onboarding-host-632f090b32664e/tree-v2-challenge:e1eecdbed86aa7340165311fd23f87cf2148a560b90cec80ea2a027509640f61
